import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../services/ad_service.dart';
import '../../services/analytics/analytics_service.dart';
import '../../services/analytics/mock_analytics_service.dart';
import '../../services/auth/auth_service.dart';
import '../../services/auth/mock_auth_service.dart';
import '../../services/backend/backend_api_client.dart';
import '../../services/backend/economy_sync_service.dart';
import '../../services/backend/mock_backend_api_client.dart';
import '../../services/backend/mock_economy_sync_service.dart';
import '../../services/backend/mock_remote_config_service.dart';
import '../../services/backend/mock_user_profile_service.dart';
import '../../services/backend/remote_config_service.dart';
import '../../services/backend/user_profile_service.dart';
import '../../services/cloud/cloud_save_service.dart';
import '../../services/cloud/mock_cloud_save_service.dart';
import '../../services/crash/crash_service.dart';
import '../../services/crash/mock_crash_service.dart';
import '../../services/iap/iap_service.dart';
import '../../services/iap/mock_iap_service.dart';
import '../../services/mock_ad_service.dart';
import '../../services/notification/mock_notification_service.dart';
import '../../services/notification/notification_service.dart';

final adServiceProvider = Provider<AdService>((ref) => const MockAdService());
final iapServiceProvider = Provider<IapService>((ref) => MockIapService());
final analyticsServiceProvider = Provider<AnalyticsService>((ref) => MockAnalyticsService());
final crashServiceProvider = Provider<CrashService>((ref) => MockCrashService());
final cloudSaveServiceProvider = Provider<CloudSaveService>((ref) => MockCloudSaveService());
final authServiceProvider = Provider<AuthService>((ref) => MockAuthService());
final remoteConfigServiceProvider = Provider<RemoteConfigService>((ref) => MockRemoteConfigService());
final notificationServiceProvider = Provider<NotificationService>((ref) => MockNotificationService());
final backendApiClientProvider = Provider<BackendApiClient>((ref) => MockBackendApiClient());
final userProfileServiceProvider = Provider<UserProfileService>((ref) => MockUserProfileService());
final economySyncServiceProvider = Provider<EconomySyncService>((ref) => MockEconomySyncService());
